version: "3"
volumes:
  redis-data:
  pg-data:
  mysql-data:
  mongodb-data:
networks:
  backend-network:
    driver: bridge
services:
  &service-mysql mysql8:
    container_name: *service-mysql
    hostname: *service-mysql
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    # temporary open ports
    ports:
      - "3306:3306"
    volumes:
      - ./log/mysql:/var/log/mysql:rw
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Parol123loraP
    networks:
      - backend-network
  &service-redis redis:
    container_name: *service-redis
    image: redis:5.0-alpine
    ports:
      - "6379:6379"
    networks:
      - backend-network
    volumes:
      - redis-data:/data:rw
  &service-php-fpm php-fpm:
    container_name: *service-php-fpm
    hostname: *service-php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www:rw
    networks:
      - backend-network
    links:
      - *service-mysql
      - *service-redis
    depends_on:
      - *service-mysql
      - *service-redis
  &service-php-cli php-cli:
    container_name: *service-php-cli
    hostname: *service-php-cli
    build:
      context: ./docker/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www:rw
      - ./.ssh/id_rsa.pub:/root/.ssh/authorized_keys
    networks:
      - backend-network
    links:
      - *service-mysql
      - *service-redis
    depends_on:
      - *service-mysql
      - *service-redis
      - *service-php-fpm
    ports:
      - "2222:22"
    environment:
    # see @link https://github.com/CasparOne/docker-sshd
      #SSH_USERS:
        #www:48:48
        #admin:1000:1000
      SSH_ENABLE_ROOT: "true"
      #MOTD:
      #SFTP_MODE: "false"
      #SFTP_CHROOT: "/data"
      #GATEWAY_PORTS: "false"
  &service-nginx nginx:
    restart: always
    container_name: *service-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - *service-php-fpm
    volumes:
      - ./src:/var/www
      - ./log/nginx:/var/log/nginx:rw
    ports:
      - "80:80"
      - "443:443"
    links:
      - *service-php-fpm
    networks:
      - backend-network
