version: "3"
networks:
  backend-network:
    driver: bridge
services:
  &service-nginx nginx:
    container_name: *service-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
      - ./log/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
    networks:
      - backend-network
  &service-php-fpm php-fpm:
    container_name: *service-php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    networks:
      - backend-network